### PR TITLE
Comments no more highlighted 

### LINKED ISSUE #7: comments are also colorized
Colors still there when  the code is commented.

### PR DESCRIPTION
**Pull request by helix026**
The patch replaces comments in received copy of editor text with equal length string of spaces, thus avoids comments being considered as part of code. Fixes #7

### CODE REVIEW

**Comment by helix026** [comment]
This commit fixes #7

**Comment by helix026** [comment]
It's been quite a while since I have opened the request... Could you review it please? :sweat:

**Comment by voldemortensen** [comment]
I'm reviewing it now. Been busy with a new job lately.

**Comment by voldemortensen** [comment]
@helix026 I just released a new version with your changes. Thanks for contributing!

https://marketplace.visualstudio.com/items?itemName=voldemortensen.rainbow-tags

**Comment by helix026** [comment]
Proud to be a contributor! :celebrate:

**Pull request merged**
